### PR TITLE
Icons: Remove extra icon sizes

### PR DESCRIPTION
**Pull request by BrainBlasted**
With the new icon guidlines for GNOME, apps only need to ship a scalable and symbolic icon, meaning that apps no longer need to export to different sizes.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
We don't even have a correct icon :P I just used the Authenticator for now to make it possible to build the flatpak package :/

**Comment by bilelmoussaoui** [comment]
Could you also remove the `qrscanner-symbolic` that I have left there too?

**Comment by BrainBlasted** [comment]
> Could you also remove the qrscanner-symbolic that I have left there too?

Sure :)

**Comment by BrainBlasted** [comment]
Done :)

**Comment by bilelmoussaoui** [comment]
Thanks! :+1:

**Pull request merged**
